---
server:
    install: '1'
    packages: [vim, htop, iotop, git]
    timezone: Europe/Berlin
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1' }
nginx:
    install: '1'
    docroot: /vagrant/www
    servername: myApp.vb
mysql:
    install: '1'
    root_password: '123'
    database: db
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages:
      - php5-cli
      - php5-intl
      - php5-mcrypt
      - php5-mysql
      - php5-curl
      - php5-dbg
      - php5-intl
      - php5-geoip
      - php5-imagick
      - php5-memcache
      - php5-mongo
      - php5-readline
      - php5-redis
      - php5-gd
      - php5-sqlite
    custom_packages:
      - curve25519
      - protobuf
